### ISSUE TITLE
Text references blockchain.info although it isn't used anymore

### ISSUE THREAD

**Issue by lukejahnke** [satoshilabs/mytrezor-l10n#4]
The msgid "Transaction info at blockchain.info" is no longer needed. I'm assuming this is the text that is displayed when hovering over the time in the transactions table.

Instead the text should dynamically reference the appropriate hosts (bitcore1.trezor.io, zec-bitcore1.trezor.io, etc) or something else more user friendly perhaps.

**Comment by karelbilek** [comment]
Thanks for noticing! :+1:

**Comment by karelbilek** [comment]
Solved. Thanks for noticing.
